---
groups:
  - name: nginx_alerts
    rules:
      - alert: NginxDown
        expr: absent(nginx_up == 1) or nginx_process_count == 0 or nginx_systemd_status
          == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Nginx is down
          description: Nginx is not running or not responding
  - name: resource_alerts
    rules:
      - alert: HighCpuUsage
        expr: 100 * (1 - avg(rate(node_cpu_seconds_total{mode='idle'}[5m])) BY
          (instance)) > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage
          description: CPU usage is above 90%
      - alert: HighRamUsage
        expr: (node_memory_MemTotal - node_memory_MemFree - node_memory_Cached) /
          node_memory_MemTotal * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High RAM usage
          description: RAM usage is above 90%

